export default function Notification() {
    return (
        <div className='m-6'>
            <span className='bg-slate-400 px-4 py-2 flex flex-wrap rounded-lg bg-opacity-30 md:text-base text-sm text-blue-pixel font-oxanium w-fit'>
                The image is generated by Pixabay, so it may not correspond to the actual item name.
            </span>
        </div>
    )
}
